### ISSUE TITLE
log to stdout by default

### ISSUE THREAD

**Issue by gbolo** [gesquive/dyngo#1]
Can we log to stdout by default if no log file is specified? I know i can set log file to `/dev/stdout` but would prefer this to be the default when user explicitly chooses not to set log file. This is perfect for docker containers. Currently, stdout is only used if log level is set to verbose:

```
	if verbose {
		log.SetOutput(os.Stdout)
	}
```

I can PR this if you agree. Good job on this project btw!

**Comment by gbolo** [comment]
@gesquive if your interested in a docker image build, please see this: https://github.com/gbolo/dockerfiles/tree/master/digitalocean-ddns

**Comment by gesquive** [comment]
Nice, glad to see a docker image made for this app!

In commit acd379932def4d30188b4e53c535dfde30475c70 I have switched the default output to be stdout in the v0.2.0 version of the app.

**Comment by gbolo** [comment]
Thanks for the quick update on this @gesquive
