### ISSUE TITLE
loading config file should be optional

### ISSUE THREAD

**Issue by gbolo** [gesquive/dyngo#2]
since the config is small and everything can be specified as a `flag` or `env variable` then we should avoid forcing the binary to load a configuration file. Defaults are already hard-coded anyways. If certain required options are missing or badly configured then we can exit with an error.

Currently, when the app can't find the config it panics:
```
Error opening config:  Unsupported Config Type ""
[2018-08-19T12:43:20-04:00]  INFO config: file=
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.run(0xa7e880, 0xaa1010, 0x0, 0x0)
	/home/travis/gopath/src/github.com/gesquive/digitalocean-ddns/main.go:158 +0x646
github.com/gesquive/digitalocean-ddns/vendor/github.com/spf13/cobra.(*Command).execute(0xa7e880, 0xc420010270, 0x0, 0x0, 0xa7e880, 0xc420010270)
	/home/travis/gopath/src/github.com/gesquive/digitalocean-ddns/vendor/github.com/spf13/cobra/command.go:572 +0x234
github.com/gesquive/digitalocean-ddns/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xa7e880, 0xa1, 0xc420096bb0, 0xc42001c180)
	/home/travis/gopath/src/github.com/gesquive/digitalocean-ddns/vendor/github.com/spf13/cobra/command.go:658 +0x339
github.com/gesquive/digitalocean-ddns/vendor/github.com/spf13/cobra.(*Command).Execute(0xa7e880, 0x25, 0xc42004def0)
	/home/travis/gopath/src/github.com/gesquive/digitalocean-ddns/vendor/github.com/spf13/cobra/command.go:617 +0x2b
main.Execute(0xc4200bcc60, 0x18)
	/home/travis/gopath/src/github.com/gesquive/digitalocean-ddns/main.go:47 +0x17d
main.main()
	/home/travis/gopath/src/github.com/gesquive/digitalocean-ddns/main.go:30 +0x118
```

**Comment by gbolo** [comment]
@gesquive if you agree, I can PR a fix

**Comment by gesquive** [comment]
Technically, the config has always been optional. it was never required for the app to run. 
In commit acdbdf7695670f7178529101e969aff30e1252a6 I removed the warning about missing configs that might have been a bit misleading and added more value checks for the variables that are actually required.

Thanks for the invaluable feedback and offering to PR. I needed to update the dependencies anyways!

**Comment by gbolo** [comment]
Thanks for the quick fix @gesquive 

I can confirm that it clearly tells you what mandatory configuration option is missing now instead of panic and also that no config file is required
