### ISSUE TITLE
Feature request: Passing in multiple domains to the command line

### ISSUE THREAD

**Issue by cdrage** [gesquive/dyngo#3]
Just a small feature request!

I'd like to pass in multiple domains to the command line (comma separated), or from variables.

**Comment by cdrage** [comment]
@gesquive any suggestions?

**Comment by gesquive** [comment]
I think its a good idea. I'll get to it eventually. In the meantime, anyone is free to submit a PR and I can take a look.

**Comment by cdrage** [comment]
@gesquive Okay :) I'll dig into the code and submit a PR.
